cdr_stats/cdr/urls.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import patterns


urlpatterns = patterns('cdr.views',
    (r'^$', 'index'),
    (r'^index/$', 'index'),
    (r'^cdr_view/$', 'cdr_view'),
    (r'^cdr_export_csv/$', 'cdr_export_to_csv'),
    (r'^cdr_detail/(?P<id>\w+)/(?P<switch_id>\w+)/$', 'cdr_detail'),
    (r'^dashboard/$', 'cdr_dashboard'),
    (r'^hourly_report/$', 'cdr_report_by_hour'),
    (r'^cdr_overview/$', 'cdr_overview'),
    (r'^cdr_concurrent_calls/$', 'cdr_concurrent_calls'),
    (r'^cdr_realtime/$', 'cdr_realtime'),
    (r'^mail_report/$', 'mail_report'),
    (r'^country_report/$', 'cdr_country_report'),
    (r'^world_map/$', 'world_map_view'),
    # (r'^get_realtime_json/$', 'cdr.ajax.get_realtime_json'),
)

cdr_stats/frontend/urls.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import patterns


urlpatterns = patterns('frontend.views',
    (r'^diagnostic/$', 'diagnostic'),
    (r'^login/$', 'login_view'),
    (r'^logout/$', 'logout_view'),
    (r'^pleaselog/$', 'pleaselog'),
    # Password reset
    (r'^password_reset/$', 'cust_password_reset'),
    (r'^password_reset/done/$', 'cust_password_reset_done'),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'cust_password_reset_confirm'),
    (r'^reset/done/$', 'cust_password_reset_complete'),
)

cdr_stats/urls.py
# -*- coding: utf-8 -*-
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import url, patterns, include
from django.conf import settings
from tastypie.api import Api
from api.user_api import UserResource
from api.switch_api import SwitchResource
from api.cdr_daily_api import CdrDailyResource
from api.cdr_api import CdrResource
from cdr.urls import urlpatterns as urlpatterns_cdr
from cdr_alert.urls import urlpatterns as urlpatterns_cdr_alert
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from frontend.urls import urlpatterns as urlpatterns_frontend
from api.api_playgrounds.urls import urlpatterns as urlpatterns_api_playgrounds
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover
dajaxice_autodiscover()

try:
    admin.autodiscover()
except admin.sites.AlreadyRegistered:
    # nose imports the admin.py files during tests, so
    # the models have already been registered.
    pass
# tastypie api
tastypie_api = Api(api_name='v1')
tastypie_api.register(UserResource())
tastypie_api.register(SwitchResource())
tastypie_api.register(CdrDailyResource())
tastypie_api.register(CdrResource())


urlpatterns = patterns('',

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    (r'^i18n/', include('django.conf.urls.i18n')),

    (r'^admin_tools/', include('admin_tools.urls')),

    (r'^api/', include(tastypie_api.urls)),

    # Serve static
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),

    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', \
                            {'url': 'static/cdr_stats/images/favicon.ico'}),
    (r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
)


urlpatterns += urlpatterns_cdr
urlpatterns += urlpatterns_cdr_alert
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_api_playgrounds
urlpatterns += urlpatterns_frontend_notification

cdr_stats/cdr/forms.py
# -*- coding: utf-8 -*-

#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django import forms
from django.conf import settings
from django.core.validators import validate_email
from django.utils.translation import ugettext_lazy as _
from common.common_functions import comp_day_range
from cdr.functions_def import get_switch_list, get_country_list, get_hc_list
from cdr.constants import STRING_SEARCH_TYPE_LIST
from user_profile.models import UserProfile

COMPARE_LIST = ((2, '>'),
    (3, '>='),
    (4, '<'),
    (5, '<='),
    (1, '='),)

PAGE_SIZE_LIST = ((10, '10'),
    (25, '25'),
    (50, '50'),
    (100, '100'),
    (250, '250'),
    (500, '500'),
    (1000, '1000'))


def sw_list_with_all():
    """Switch list"""
    list_sw = []
    list_sw.append((0, _('All Switches')))
    sw_list = get_switch_list()
    for i in sw_list:
        list_sw.append((i[0], i[1]))
    return list_sw


def hc_list_with_all():
    """Hangup cause list"""
    list_hc = []
    list_hc.append((0, _('All')))
    hc_list = get_hc_list()
    for i in hc_list:
        list_hc.append((i[0], i[1]))
    return list_hc


def country_list_with_all():
    """Country list"""
    list_ct = []
    list_ct.append((0, _('All')))
    list_ct.append((999, _('Internal Call')))
    ct_list = get_country_list()
    for i in ct_list:
        list_ct.append((i[0], i[1]))
    return list_ct


class SearchForm(forms.Form):
    """
    Form used to search on general parameters in the Customer UI.
    """

    caller = forms.CharField(label=_('CallerID Number'), required=False)
    caller_type = forms.ChoiceField(label='', required=False,
                                    choices=list(STRING_SEARCH_TYPE_LIST))
    caller_type.widget.attrs['class'] = 'input-small'

    destination = forms.CharField(label=_('Destination'),
                                  required=False)
    destination_type = forms.ChoiceField(label='',
                                         required=False,
                                         choices=list(STRING_SEARCH_TYPE_LIST))
    destination_type.widget.attrs['class'] = 'input-small'
    accountcode = forms.CharField(label=_('Account Code'),
                                  required=False)
    accountcode_type = forms.ChoiceField(label='',
                                         required=False,
                                         choices=list(STRING_SEARCH_TYPE_LIST))
    accountcode_type.widget.attrs['class'] = 'input-small'
    duration = forms.CharField(label=_('Duration (Secs)'),
                               required=False)
    duration_type = forms.ChoiceField(label='',
                                      required=False,
                                      choices=COMPARE_LIST)
    duration_type.widget.attrs['class'] = 'input-small'
    hangup_cause = forms.ChoiceField(label=_('Hangup cause'),
                                     required=False,
                                     choices=hc_list_with_all())
    switch = forms.ChoiceField(label=_('Switch'),
                               required=False,
                               choices=get_switch_list())
    country_id = forms.MultipleChoiceField(label=_('Country'), required=False,
                                           choices=country_list_with_all())

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields['switch'].choices = sw_list_with_all()

    def clean_duration(self):
        """Retrieve valid duration & it should be integer
        else will raise from validation error
        """
        duration = self.cleaned_data['duration']
        if duration:
            try:
                int(duration)
            except:
                raise forms.ValidationError('%s is not a valid duration.'
                    % duration)
        return duration

    def clean_accountcode(self):
        """Retrieve valid accountcode"""
        accountcode = self.cleaned_data['accountcode']
        return accountcode


class CdrSearchForm(SearchForm):
    """
    Form used to search calls in the Customer UI.
    """
    from_date = forms.CharField(label=_('From'),
                                required=True, max_length=10)
    to_date = forms.CharField(label=_('To'),
                              required=True, max_length=10)
    direction = forms.TypedChoiceField(label=_('Direction'),
                                       required=False,
                                       coerce=bool,
                                       choices=(('all', _('All')),
                                       ('inbound', _('Inbound')),
                                       ('outbound', _('Outbound')),
                                       ('unknown', _('Unknown'))))
    result = forms.TypedChoiceField(label=_('Result'),
                                    required=False,
                                    coerce=bool,
                                    choices=((1, _('Minutes')),
                                    (2, _('Seconds'))),
                                    widget=forms.RadioSelect)
    records_per_page = forms.ChoiceField(label=_('CDR per page'),
                                         required=False,
                                         initial=settings.PAGE_SIZE,
                                         choices=PAGE_SIZE_LIST)
    records_per_page.widget.attrs['class'] = 'input-mini'

    def __init__(self, *args, **kwargs):
        super(CdrSearchForm, self).__init__(*args, **kwargs)
        self.fields['records_per_page'].widget.attrs['onchange'] = \
            'this.form.submit();'


class CountryReportForm(CdrSearchForm):
    """
    Form used to get country vise calls report in the Customer UI.
    """
    def __init__(self, *args, **kwargs):
        super(CountryReportForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['from_date', 'to_date', 'country_id',
                                'duration', 'duration_type', 'switch']


class CdrOverviewForm(CdrSearchForm):
    """
    Form used to get overview of calls in the Customer UI.
    """
    def __init__(self, *args, **kwargs):
        super(CdrOverviewForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['from_date', 'to_date', 'switch']


class CompareCallSearchForm(SearchForm):
    """
    Form used to search calls for comparison in the Customer UI.
    """
    from_date = forms.CharField(label=_('Select date'), required=True,
                                max_length=10)

    comp_days = forms.ChoiceField(label='', required=False,
                                  choices=comp_day_range(6))
    comp_days.widget.attrs['class'] = 'input-small'
    graph_view = forms.ChoiceField(label=_('Graph'), required=False,
                                   choices=((1, _('Calls per Hour')), (2,
                                   _('Minutes per Hour'))))
    check_days = forms.TypedChoiceField(label=_('Check with'), required=False,
            coerce=bool, choices=((1, _('Previous days')), (2,
            _('Same day of the week'))), widget=forms.RadioSelect)

    def __init__(self, *args, **kwargs):
        super(CompareCallSearchForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['from_date', 'comp_days', 'check_days',
                                'graph_view', 'switch']


class ConcurrentCallForm(CdrSearchForm):
    """
    Form used for concurrent calls in the Customer UI.
    """
    def __init__(self, *args, **kwargs):
        super(ConcurrentCallForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['from_date', 'result', 'switch']
        self.fields['from_date'].label = _('Select date')


class SwitchForm(SearchForm):
    """
    Form used to get the list of switches in the Customer UI.
    """
    def __init__(self, *args, **kwargs):
        super(SwitchForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['switch']
        self.fields['switch'].widget.attrs['onchange'] = 'this.form.submit();'


class WorldForm(CdrSearchForm):
    """
    Form used to get world overview of calls in the Customer UI.
    """
    def __init__(self, *args, **kwargs):
        super(WorldForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['from_date', 'to_date', 'switch']


class EmailReportForm(forms.ModelForm):
    """
    Form used to change the detail of a user in the Customer UI.
    """
    multiple_email = forms.CharField(max_length=300, required=False,
        label=_('Email to send the report'))
    multiple_email.widget.attrs['class'] = 'span6'

    class Meta:
        model = UserProfile
        fields = ('multiple_email', )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(EmailReportForm, self).__init__(*args, **kwargs)

    def clean_multiple_email(self):
        """Check that the field contains one or more comma-separated emails
        and normalizes the data to a list of the email strings.
        """
        emails = self.cleaned_data['multiple_email'].split(',')
        mail_list = []
        for email in emails:
            email = email.strip()
            try:
                validate_email(email)
                mail_list.append(str(email))
            except:
                raise forms.ValidationError('%s is not a valid e-mail address.'
                         % email)

        # Always return the cleaned data.
        mail_list = ','.join(mail_list)
        return mail_list


class FileImport(forms.Form):
    """General Form : CSV file upload"""

    csv_file = forms.FileField(label=_('Upload CSV File '), required=True,

cdr_stats/frontend/forms.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django import forms
from django.utils.translation import ugettext_lazy as _


class LoginForm(forms.Form):
    """Client Login Form"""
    user = forms.CharField(max_length=30,
        label=_('Username:'), required=True)
    user.widget.attrs['class'] = 'input-small'
    user.widget.attrs['placeholder'] = 'Username'
    password = forms.CharField(max_length=30, label=_('Password:'),
                               required=True,
                               widget=forms.PasswordInput())
    password.widget.attrs['class'] = 'input-small'
    password.widget.attrs['placeholder'] = 'Password'

cdr_stats/templates/frontend/cdr_detail_asterisk.html
{% extends "frontend/master.html" %}
{% load i18n cdr_extras common_tags %}


{% block content %}
{% for element in row %}

    <p><pre>{{ element }}</pre></p>

{% endfor %}
{% endblock %}

cdr_stats/templates/frontend/cdr_detail_freeswitch.html
{% extends "frontend/master.html" %}
{% load i18n cdr_extras common_tags %}

{% block content %}

{% for element in row %}
    <p>{% trans "FreeSWITCH CDR" %} :<pre>{{ element }}</pre></p>
    <p>{% trans "channel data"|title %} : <pre>{{ element.channel_data|to_json }}</pre></p>
    <p>{% trans "callflow"|title %} : <pre>{{ element.callflow|to_json }}</pre></p>
    <p>{% trans "app log"|title %} : <pre>{{ element.app_log|to_json }}</pre></p>
    <p>{% trans "variables"|title %} : <pre>{{ element.variables|to_json }}</pre></p>
{% endfor %}

{% endblock %}

cdr_stats/templates/frontend/cdr_mail_report.html
{% extends "frontend/master.html" %}
{% load i18n cdr_extras common_tags %}

{% block title %}{% trans "CDR Mail Report" %}{% endblock %}

{% block content %}
    {% if msg %}
        <div class="alert alert-success">
            <strong>{% trans "Alert" %} : </strong>  {{ msg }}
        </div>
    {% endif %}

    <form class="well" method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span6" style="width:510px;">
                    <div class="control-group">
                        <label class="control-label" for="{{ form.multiple_email.auto_id }}">{{ form.multiple_email.label }} :</label>
                    </div>
                </div>
                <div class="span6">
                    <div class="controls">
                        {{ form.multiple_email }}
                        {% if form.multiple_email.errors %}
                            <span class="help-inline">{{ form.multiple_email.errors }}</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <label></label>
    <div class="actions">
        <input type="submit" class="btn btn-primary" name="save" value={% trans "Save" %} />
    </div>
    </form>

    <p>&nbsp;</p>

    <h2>{% trans "Preview of the mail report" %} :</h2>
    <hr/>

    {% include 'frontend/mail_report_template.html' %}

{% endblock %}

cdr_stats/templates/frontend/custom_jquery_select_all.html
{% load i18n cdr_extras %}

<script type="text/javascript" language="javascript">
function toggleChecked(status) {
    $(".checkbox").each( function() {
        $(this).attr("checked", status);
    })
}

$(document).ready(function() {
    $('#ListForm').submit(function(e) {

        var currentForm = this;
        e.preventDefault();

        var $fields = $(this).find('input[name="select"]:checked');

        if (!$fields.length) {
            msg = '{% trans "You must check at least one box!" %}';
            bootbox.alert(msg);
            return false; // The form will *not* submit
        }
        else
        {
            var confirm_string;
            var contact_count;

            if(document.location.href.search("/alert/") != -1) {
                confirm_string =  $fields.length + '{% trans " alarms(s) are going to be deleted?" %}';
            }

            bootbox.confirm(confirm_string, function(result) {
                if (result) {
                    currentForm.submit();
                }
            });

            return false;
        }
    });

    $('#id_delete_confirm').click(function(e) {
        e.preventDefault();
        var href = this.href;
        confirm_string = '{% trans "Confirm deletion?" %}';
        bootbox.confirm(confirm_string, function(result){
            if (result) {
                window.location = href;
            }
        });
        return false;
    });
});

</script>

cdr_stats/templates/frontend/footer.html
    <footer>
        <p>Powered by CDR-Stats - <a href="http://www.cdr-stats.org/" target="_blank">Call Monitoring & Analytics Software</a></p>
    </footer>

cdr_stats/templates/frontend/login.html
<script type="text/javascript">
      $(function(){

        $('#buttonlogin').click(function(){
          $("#requestlogin").animate({ height: 'show', opacity: 'show' }, 'slow');
          $("#buttonlogin").animate({ height: 'hide', opacity: 'hide' }, 'fast');
        });
        $('#buttonlogout').click(function(){
          $('#logout').submit();
        });
      });
</script>


{% block login %}
    <div id="requestlogin" style="margin: 10px; padding: 10px;  width: 180px; height: 80px; float : left; display: none; " class="ui-widget ui-widget-content ui-corner-all">
        <form action="/login/" method="post">
            {% csrf_token %}
            {% for field in loginform %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }}: {{ field }}
            </div>
            {% endfor %}d
            <input type="submit" value="login" class="ui-state-default">
        </form>
    </div>
{% endblock login %}

cdr_stats/templates/frontend/world_map_analytic.html
{% extends "frontend/master.html" %}
{% load i18n cdr_extras country_dialcode_tags common_tags %}

{% block extra_head %}
    <script type="text/javascript">
        $(function() {
            var dates = $('#id_from_date, #id_to_date').datepicker({
                defaultDate: "+1w",
                changeMonth: true,
                format: 'yyyy-mm-dd',
                onSelect: function(selectedDate) {
                    var option = this.id == "id_from_date" ? "minDate" : "maxDate";
                    var instance = $(this).data("datepicker");
                    var date = $.datepicker.parseDate(instance.settings.format || $.datepicker._defaults.format, selectedDate, instance.settings);
                    dates.not(this).datepicker("option", option, date);
                }
            });
        });
    </script>
    <!--css-->
    <link type="text/css" media="screen" href="{{STATIC_URL}}cdr-stats/js/jquery.vector-map/jquery.vector-map.css" rel="stylesheet">
    <!-- Javascript -->
    <script type="text/javascript" src="{{STATIC_URL}}cdr-stats/js/jquery.vector-map/jquery.vector-map.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}cdr-stats/js/jquery.vector-map/world-en.js"></script>
    <script type="text/javascript">
        $(function(){
            // sample country call data
            var call_data = [
                {% for rc in world_analytic_array %}
                    {
                        label: '{{ rc.1 }}',
                        data: [{{ rc.2 }}, {{ rc.3 }}]
                    },
                {% endfor %}
            ];
            values = {};

            {% for rc in world_analytic_array %}
                values['{{ rc.1 }}'] = '{{ rc.2 }}';
            {% endfor %}

            function conve_min(val)
            {
                if(val != 0)
                {
                    var minutes = Math.floor(val / 60); // 7
                    var seconds = val % 60; // 30
                    return String(minutes +':'+seconds+' minutes')
                }
                else
                {return String('00:00 minutes');}

            }

            $('#call-world-map').vectorMap({
                backgroundColor: '#DDECEF',
                map: 'world_en',
                values: values,
                scaleColors: ['#C7AFBD', '#484452'],
                hoverOpacity: 0.7,
                hoverColor: false,
                onLabelShow: function(event, label, code){
                    for (var k in call_data) {
                        if (!call_data.hasOwnProperty(k)) continue;
                        if(call_data[k].label == code)
                        {
                            var temp_string = label.text();
                            temp_string = temp_string + " : " + String(call_data[k].data[0])+ " Calls - " + conve_min(parseInt(call_data[k].data[1]));
                            label.text(temp_string);
                            break;
                        }
                    }
                }
            });
        });
    </script>

{% endblock %}

{% block content %}
<div class="tabbable">
    <ul class="nav nav-tabs">
        <li {% if action == "tabs-1" %}class="active"{% endif %}><a href="#tabs-1" data-toggle="tab">{% trans "country calls detail"|title %}</a></li>
        <li {% if action == "tabs-2" %}class="active"{% endif %}><a href="#tabs-2" data-toggle="tab">{% trans "country list"|title %}</a></li>
    </ul>

    <div id="form_collapse" class="collapse">
        <form class="well" method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
            <div class="row">
                <div class="span12">
                    <div class="row">
                        <div class="span4">
                            <label class="control-label" for="id_{{ form.from_date.name }}">{{ form.from_date.label }}</label>
                            <div class="input">
                                {{ form.from_date }}
                                <span class="help-block">{{ form.from_date.help_text|safe }} </span>
                            </div>
                        </div>
                        <div class="span4">
                            <label class="control-label" for="id_{{ form.to_date.name }}">{{ form.to_date.label }}</label>
                            <div class="input">
                                {{ form.to_date }}
                                <span class="help-block">{{ form.to_date.help_text|safe }} </span>
                            </div>
                        </div>
                        <div class="span4">
                            <label class="control-label" for="id_{{ form.switch.name }}">{{ form.switch.label }}</label>
                            <div class="input">
                                {{ form.switch }}
                                <span class="help-block">{{ form.switch.help_text|safe }} </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <label></label>
            <div class="actions">
                <input type="submit" class="btn btn-primary" name="search" value={% trans "Search" %} />
            </div>
        </form>
    </div>

    <a class="btn btn-small" id="toggle_btn" href="#" data-toggle="collapse" data-target="#form_collapse">
        <i class="icon-search"></i> <span>{% trans "advanced search"|title %}</span>
    </a>

    <div class="tab-content">
        <div id="tabs-1" class="tab-pane {% if action == "tabs-1" or action == "" %}active{% endif %}">
            <div class="row">
                <div class="span12">
                    <div class="graph_header">
                        <span id="id_title_span">{% trans "World map Report"|title %}</span> -
                        <b>
                            {% if start_date  %}
                                {{ start_date|date:"jS N Y" }}
                            {% endif %}
                            {% if end_date  %}
                                {% trans "to" %} {{ end_date|date:"jS N Y" }}
                            {% endif %}
                        </b>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    <div id="call-world-map" style="margin:auto; width: 1150px; height: 500px"></div>
                </div>
            </div>
        </div>

        <div id="tabs-2" class="tab-pane {% if action == "tabs-2" %}active{% endif %}">
            <table class="table table-striped table-bordered table-condensed">
                <thead>
                <tr>
                    <th>{% trans "Country"  %}</th>
                    <th>{% trans "Calls"  %}</th>
                    <th>{% trans "Duration"  %}</th>
                </tr>
                </thead>
                <tbody>
                {% for country_data in world_analytic_array %}
                    <tr>
                        <td>
                            {% if country_data.0 %}
                                <img src="{{STATIC_URL}}cdr-stats/{{ country_data.0|iso_flag }}" class="elemtooltip" title="{{ country_data.0|country_name }}">
                                {{ country_data.4 }}
                            {% else %}
                                <img src="{{STATIC_URL}}cdr-stats/icons/world.png" class="elemtooltip" title="{% trans "World" %}">
                                {% trans "world"|title  %}
                            {% endif %}
                        </td>
                        <td>{{ country_data.2 }} {% trans "Calls"%}</td>
                        <td>{{ country_data.3|conv_min }} {% trans "minutes"%}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}