cdr_stats/cdr_alert/urls.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import patterns

urlpatterns = patterns('cdr_alert.views',
     # User detail change for Customer UI
     (r'^alert/$', 'alarm_list'),
     (r'^alert/add/$', 'alarm_add'),
     (r'^alert/del/(.+)/$', 'alarm_del'),
     (r'^alert/(.+)/$', 'alarm_change'),

     (r'^trust_control/$', 'trust_control'),
     (r'^alert_report/$', 'alert_report'),
)

cdr_stats/frontend/urls.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import patterns


urlpatterns = patterns('frontend.views',
    (r'^diagnostic/$', 'diagnostic'),
    (r'^login/$', 'login_view'),
    (r'^logout/$', 'logout_view'),
    (r'^pleaselog/$', 'pleaselog'),
    # Password reset
    (r'^password_reset/$', 'cust_password_reset'),
    (r'^password_reset/done/$', 'cust_password_reset_done'),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'cust_password_reset_confirm'),
    (r'^reset/done/$', 'cust_password_reset_complete'),
)

cdr_stats/urls.py
# -*- coding: utf-8 -*-
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import url, patterns, include
from django.conf import settings
from tastypie.api import Api
from api.user_api import UserResource
from api.switch_api import SwitchResource
from api.cdr_daily_api import CdrDailyResource
from api.cdr_api import CdrResource
from cdr.urls import urlpatterns as urlpatterns_cdr
from cdr_alert.urls import urlpatterns as urlpatterns_cdr_alert
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from frontend.urls import urlpatterns as urlpatterns_frontend
from api.api_playgrounds.urls import urlpatterns as urlpatterns_api_playgrounds
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover
dajaxice_autodiscover()

try:
    admin.autodiscover()
except admin.sites.AlreadyRegistered:
    # nose imports the admin.py files during tests, so
    # the models have already been registered.
    pass
# tastypie api
tastypie_api = Api(api_name='v1')
tastypie_api.register(UserResource())
tastypie_api.register(SwitchResource())
tastypie_api.register(CdrDailyResource())
tastypie_api.register(CdrResource())


urlpatterns = patterns('',

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    (r'^i18n/', include('django.conf.urls.i18n')),

    (r'^admin_tools/', include('admin_tools.urls')),

    (r'^api/', include(tastypie_api.urls)),

    # Serve static
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),

    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', \
                            {'url': 'static/cdr_stats/images/favicon.ico'}),
    (r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
)


urlpatterns += urlpatterns_cdr
urlpatterns += urlpatterns_cdr_alert
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_api_playgrounds
urlpatterns += urlpatterns_frontend_notification

cdr_stats/cdr_alert/models.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from country_dialcode.models import Country
from cdr_alert.constants import PERIOD, STATUS, ALARM_TYPE, \
    ALERT_CONDITION, ALERT_CONDITION_ADD_ON, ALARM_REPROT_STATUS


class AlertRemovePrefix(models.Model):
    """This defines the Alert Remove Prefix
    Define the list of prefixes that need to be removed from the dialed digits, 
    assuming the phone numbers are in the format 5559004432, with the signifcant digits
    9004432, the prefix 555 needs to be removed to analyse the phone numbers.

    **Attributes**:

        * ``label`` - Label for the custom prefix
        * ``prefix`` - Prefix value

    **Name of DB table**: alarm
    """
    label = models.CharField(max_length=100, verbose_name=_('Label'))
    prefix = models.CharField(max_length=100, unique=True,
                              verbose_name=_('Prefix'))
    created_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name=_('Date'))
    updated_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s' % (self.label)

    class Meta:
        verbose_name = _("Alert Remove Prefix")
        verbose_name_plural = _("Alert Remove Prefixes")
        db_table = "alert_remove_prefix"


class Alarm(models.Model):
    """This defines the Alarm

    **Attributes**:

        * ``user`` -
        * ``name`` - Alarm name
        * ``period`` - Day | Week | Month
        * ``type`` - ALOC (average length of call) ; ASR (answer seize ratio)
        * ``alert_condition`` -
        * ``alert_value`` - Input the value for the alert
        * ``alert_condition_add_on`` -
        * ``status`` - Inactive | Active
        * ``email_to_send_alarm`` - email_to

    **Name of DB table**: alert
    """
    user = models.ForeignKey('auth.User', related_name='Alarm_owner')
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    period = models.PositiveIntegerField(choices=list(PERIOD), default=1,
                                verbose_name=_('Period'),
                                help_text=_('Interval to apply alarm'))
    type = models.PositiveIntegerField(choices=list(ALARM_TYPE), default=1,
                                verbose_name=_('Type'),
                                help_text=_('ALOC (average length of call) ; ASR (answer seize ratio) ; CIC (Consecutive Incomplete Calls) '))
    alert_condition = models.PositiveIntegerField(choices=list(ALERT_CONDITION),
                                                  default=1,
                                                  verbose_name=_('Condition'))
    alert_value = models.DecimalField(verbose_name=_('Value'), max_digits=5,
                                decimal_places=2, blank=True, null=True,
                                help_text=_('Input the value for the alert'))
    alert_condition_add_on = models.PositiveIntegerField(choices=list(ALERT_CONDITION_ADD_ON),
                                                         default=1)
    status = models.PositiveIntegerField(choices=list(STATUS), default=1,
                                         verbose_name=_('Status'))

    email_to_send_alarm = models.EmailField(max_length=100,
                                    verbose_name=_('Email to send alarm'))
    created_date = models.DateTimeField(auto_now_add=True,
                                        verbose_name=_('Date'))
    updated_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s' % (self.name)

    class Meta:
        permissions = (
            ("alert_settings", _('Can see alarms')),
        )
        verbose_name = _("Alarm")
        verbose_name_plural = _("Alarms")
        db_table = "alert"


class AlarmReport(models.Model):
    """This defines the Alarm report

    **Attributes**:

        * ``alarm`` - Alarm name
        * ``calculatedvalue`` - Input the value for the alert
        * ``daterun`` -

    **Name of DB table**: alert_report
    """
    alarm = models.ForeignKey(Alarm, verbose_name=_('Alarm'),
                              help_text=_("Select Alarm"))
    calculatedvalue = models.DecimalField(verbose_name=_('Calculated value'),
                                          max_digits=10, decimal_places=3,
                                          blank=True, null=True)
    status = models.PositiveIntegerField(choices=list(ALARM_REPROT_STATUS),
                        default=1, verbose_name=_('Status'))

    daterun = models.DateTimeField(auto_now=True, verbose_name=_('Date'))

    def __unicode__(self):
        return '%s' % (self.alarm)

    class Meta:
        permissions = (
            ("alarm_report", _('Can see alarm report')),
        )
        verbose_name = _("Alarm Report")
        verbose_name_plural = _("Alarms Report")
        db_table = "alert_report"


class Blacklist(models.Model):
    """This defines the Blacklist

    **Attributes**:

        * ``user`` -
        * ``phonenumber_prefix`` -
        * ``country`` -

    **Name of DB table**: alert_blacklist
    """
    user = models.ForeignKey('auth.User', related_name='Blacklist_owner')
    phonenumber_prefix = models.PositiveIntegerField(blank=False, null=False)
    country = models.ForeignKey(Country, null=True, blank=True,
                                verbose_name=_("Country"),
                                help_text=_("Select Country"))

    def __unicode__(self):
        return '[%s] %s' % (self.id, self.phonenumber_prefix)

    class Meta:
        permissions = (
            ("view_blacklist", _('Can see blacklist country/prefix')),
        )
        verbose_name = _("Blacklist")
        verbose_name_plural = _("Blacklist")
        db_table = "alert_blacklist"


class Whitelist(models.Model):
    """This defines the Blacklist

    **Attributes**:

        * ``user`` -
        * ``phonenumber_prefix`` -
        * ``country`` -

    **Name of DB table**: alert_whitelist
    """
    user = models.ForeignKey('auth.User', related_name='whitelist_owner')
    phonenumber_prefix = models.PositiveIntegerField(blank=False, null=False)
    country = models.ForeignKey(Country, null=True, blank=True,
                                verbose_name=_("Country"),
                                help_text=_("Select Country"))

    def __unicode__(self):
        return '[%s] %s' % (self.id, self.phonenumber_prefix)

    class Meta:
        permissions = (
            ("view_whitelist", _('Can see whitelist country/prefix')),
        )
        verbose_name = _("Whitelist")
        verbose_name_plural = _("Whitelist")
        db_table = "alert_whitelist"

cdr_stats/cdr_alert/forms.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _
from cdr_alert.models import Alarm, Blacklist, Whitelist
from cdr.functions_def import get_country_list


class BWCountryForm(forms.Form):
    """Blacklist/Whitelist by country form"""
    country = forms.ChoiceField(label=_('Country'), required=True,
                                choices=get_country_list())

    def __init__(self, *args, **kwargs):
        super(BWCountryForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['country']


class BWPrefixForm(forms.Form):
    """Blacklist/Whitelist by prefix form"""
    prefix = forms.CharField(label=_('Prefix'), required=False)

    def __init__(self, *args, **kwargs):
        super(BWPrefixForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['prefix']


class AlarmForm(ModelForm):
    """Alarm ModelForm"""

    class Meta:
        model = Alarm
        fields = ['name', 'period', 'type', 'alert_condition',
                  'alert_value', 'alert_condition_add_on', 'status',
                  'email_to_send_alarm']
        exclude = ('user',)


class AlarmReportForm(forms.Form):
    """alarm list form"""
    alarm = forms.ChoiceField(label=_("Alert"), required=False)

    def __init__(self, user, *args, **kwargs):
        super(AlarmReportForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['alarm']

        alarm_list_user = []
        alarm_list_user.append((0, '---'))
        alarm_list = Alarm.objects.values_list('id', 'name')\
            .filter(user=user).order_by('id')
        for i in alarm_list:
            alarm_list_user.append((i[0], i[1]))

        self.fields['alarm'].choices = alarm_list_user

cdr_stats/frontend/forms.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django import forms
from django.utils.translation import ugettext_lazy as _


class LoginForm(forms.Form):
    """Client Login Form"""
    user = forms.CharField(max_length=30,
        label=_('Username:'), required=True)
    user.widget.attrs['class'] = 'input-small'
    user.widget.attrs['placeholder'] = 'Username'
    password = forms.CharField(max_length=30, label=_('Password:'),
                               required=True,
                               widget=forms.PasswordInput())
    password.widget.attrs['class'] = 'input-small'
    password.widget.attrs['placeholder'] = 'Password'

cdr_stats/templates/frontend/cdr_alert/common_black_white_list.html
{% extends "frontend/master.html" %}
{% load i18n common_tags dajaxice_templatetags %}

{% block title %}{% trans "Trust control"|title %}{% endblock %}

{% block extra_head %}
    {% dajaxice_js_import %}
    <script src="{{ STATIC_URL }}cdr-stats/js/jquery.dajax.core.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}cdr-stats/js/jquery.ba-serializeobject.js" type="text/javascript"></script>
    <script type="text/javascript">
        // toggle Checkbox blacklist
        function toggleChecked_blacklist(status) {
            $("#id_blacklist_table .checkbox").each( function() {
                $(this).attr("checked", status);
            })
        }

        $(function() {
            // add country id to blacklist
            $('#add_bl_country').click(function(e) {
                e.preventDefault();
                var country_id = $('#id_bl_country_from #id_country :selected').val();
                Dajaxice.cdr_alert.add_blacklist_country(Dajax.process, {'country_id': country_id});
            });

            // add dialcode to blacklist
            $('#add_bl_prefix').click(function(e) {
                e.preventDefault();
                var prefix = $('#id_bl_prefix').val();
                if (prefix == '') {
                    msg = '{% trans "You must enter dialcode" %}';
                    bootbox.alert(msg);
                } else{
                    Dajaxice.cdr_alert.add_blacklist_prefix(Dajax.process, {'prefix': prefix});
                }
            });
        });

        // toggle Checkbox whitelist
        function toggleChecked_whitelist(status) {
            $("#id_whitelist_table .checkbox").each( function() {
                $(this).attr("checked", status);
            })
        }

        $(function() {
            // add country id to whitelist
            $('#add_wl_country').click(function(e) {

                e.preventDefault();
                var country_id = $('#id_wl_country_from #id_country :selected').val();
                Dajaxice.cdr_alert.add_whitelist_country(Dajax.process, {'country_id': country_id});
            });
            // add dialcode to whitelist
            $('#add_wl_prefix').click(function(e) {

                e.preventDefault();
                var prefix = $('#id_wl_prefix').val();
                if (prefix == '')
                {
                    msg = '{% trans "You must enter dialcode" %}';
                    bootbox.alert(msg);
                }
                else{
                    Dajaxice.cdr_alert.add_whitelist_prefix(Dajax.process, {'prefix': prefix});
                }
            });
        });

        function delete_button(list_name)
        {
            if (list_name == 'blacklist') {
                var $fields = $('#id_blacklist_table').find('input[name="select_blacklist"]:checked');
            }
            if (list_name == 'whitelist') {
                var $fields = $('#id_whitelist_table').find('input[name="select_whitelist"]:checked');
            }

            if (!$fields.length) {
                msg = '{% trans "You must check at least one box!" %}';
                bootbox.alert(msg);
                return false; // The form will *not* submit
            } else {
                var allVals = [];
                $fields.each(function() {
                    allVals.push($(this).val());
                });
                if (list_name == 'blacklist') {
                    Dajaxice.cdr_alert.delete_blacklist(Dajax.process, {'id_list': allVals});
                }
                if (list_name == 'whitelist')
                {
                    Dajaxice.cdr_alert.delete_whitelist(Dajax.process, {'id_list': allVals});
                }
            }
            return false;
        }

        function delete_all_button(list_name)
        {
            if (list_name == 'blacklist')
            {
                Dajaxice.cdr_alert.delete_blacklist(Dajax.process, {'id_list': '0'});
            }
            if (list_name == 'whitelist')
            {
                Dajaxice.cdr_alert.delete_whitelist(Dajax.process, {'id_list': '0'});
            }
            return false;
        }

        $(function() {
            $('.typeahead').typeahead();
        });

    </script>

    {% include "frontend/custom_jquery_select_all.html" %}
    <h3>{% trans "Trust control"|title %} <small>{% trans "control the blacklist / whitelist" %}</small></h3>
{% endblock %}

{% block content %}
<div id="id_alert_message"></div>

<div class="row">
    <div class="span12">
        <h3>{% trans "blacklist"|title %}</h3>

        <div class="btn-group">
            <button class="btn">{% trans "Action" %}</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                {% if perms.cdr_alert.delete_alert  %}
                    <li><a href="#" onclick="delete_button('blacklist')">{% trans "Delete selected" %}</a></li>
                    <li><a href="#" onclick="delete_all_button('blacklist')">{% trans "Delete all" %}</a></li>
                {% endif %}
            </ul>
        </div>
        <br/><br/>
        <div id="id_blacklist_table">
            {% if blacklist %}
            <table class="table table-striped table-bordered table-condensed">
                <tr>
                    <td><input type="checkbox" onclick="toggleChecked_blacklist(this.checked);"></td>
                </tr>
                {% for row in blacklist|groupby_columns:5 %}
                    <tr>
                        {% for obj in row %}
                            {% if obj %}
                                <td><input type="checkbox" name="select_blacklist" class="checkbox" value="{{ obj.id }}" />
                                    &nbsp;{{ obj.phonenumber_prefix }} | {{ obj.country.countryname }}</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            {% endif %}
        </div>
    </div>
</div>

<div class="row">
    <div class="span12">
        <!--blacklist country form-->
        <form class="form-search" action="." id="id_bl_country_from" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in bl_country_form %}
                {{ field }}
                <input id="add_bl_country" type="button" class="btn btn-info" value="{% trans "Blacklist this country" %}" />
            {% endfor %}
        </form>

        <!--blacklist prefix form-->
        <form class="form-search" action="." id="id_bl_prefix_from" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input id="id_bl_prefix" name="prefix"  type="text" data-provide="typeahead" data-items="10" data-source='{{ prefix_list }}'>
            <input id="add_bl_prefix" type="button" class="btn btn-info" value="{% trans "Blacklist this dialcode" %}" />
        </form>
    </div>
</div>


<div class="row">
    <div class="span12">
        <h3>{% trans "whitelist"|title %}</h3>

        <div class="btn-group">
            <button class="btn">{% trans "Action" %}</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                {% if perms.cdr_alert.delete_alert  %}
                    <li><a href="#" onclick="delete_button('whitelist')">{% trans "Delete selected" %}</a></li>
                    <li><a href="#" onclick="delete_all_button('whitelist')">{% trans "Delete all" %}</a></li>
                {% endif %}
            </ul>
        </div>
        <br/><br/>
        <div id="id_whitelist_table">
            {% if whitelist %}
            <table class="table table-striped table-bordered table-condensed">
                <tr><td><input type="checkbox" onclick="toggleChecked_whitelist(this.checked);"></td></tr>
                {% for row in whitelist|groupby_columns:5 %}
                    <tr>
                        {% for obj in row %}
                            {% if obj %}
                                <td><input type="checkbox" name="select_whitelist" class="checkbox" value="{{ obj.id }}" />
                                    &nbsp;{{ obj.phonenumber_prefix }} | {{ obj.country.countryname }}</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            {% endif %}
        </div>
    </div>
</div>

<div class="row">
    <div class="span12">
        <!--whitelist country form-->
        <form class="form-search" action="." id="id_wl_country_from" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in wl_country_form %}
                {{ field }}
                <input id="add_wl_country" type="button" class="btn btn-info" value="{% trans "Whitelist this country" %}" />
            {% endfor %}
        </form>

        <!--whitelist prefix form-->
        <form class="form-search" action="." id="id_wl_prefix_from" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input id="id_wl_prefix" name="prefix"  type="text" data-provide="typeahead" data-items="10" data-source='{{ prefix_list }}'>
            <input id="add_wl_prefix" type="button" class="btn btn-info" value="{% trans "Whitelist this dialcode" %}" />
        </form>
    </div>
</div>
{% endblock %}