cdr_stats/cdr_alert/urls.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import patterns

urlpatterns = patterns('cdr_alert.views',
     # User detail change for Customer UI
     (r'^alert/$', 'alarm_list'),
     (r'^alert/add/$', 'alarm_add'),
     (r'^alert/del/(.+)/$', 'alarm_del'),
     (r'^alert/(.+)/$', 'alarm_change'),

     (r'^trust_control/$', 'trust_control'),
     (r'^alert_report/$', 'alert_report'),
)

cdr_stats/urls.py
# -*- coding: utf-8 -*-
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#

from django.conf.urls import url, patterns, include
from django.conf import settings
from tastypie.api import Api
from api.user_api import UserResource
from api.switch_api import SwitchResource
from api.cdr_daily_api import CdrDailyResource
from api.cdr_api import CdrResource
from cdr.urls import urlpatterns as urlpatterns_cdr
from cdr_alert.urls import urlpatterns as urlpatterns_cdr_alert
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from frontend.urls import urlpatterns as urlpatterns_frontend
from api.api_playgrounds.urls import urlpatterns as urlpatterns_api_playgrounds
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover
dajaxice_autodiscover()

try:
    admin.autodiscover()
except admin.sites.AlreadyRegistered:
    # nose imports the admin.py files during tests, so
    # the models have already been registered.
    pass
# tastypie api
tastypie_api = Api(api_name='v1')
tastypie_api.register(UserResource())
tastypie_api.register(SwitchResource())
tastypie_api.register(CdrDailyResource())
tastypie_api.register(CdrResource())


urlpatterns = patterns('',

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    (r'^i18n/', include('django.conf.urls.i18n')),

    (r'^admin_tools/', include('admin_tools.urls')),

    (r'^api/', include(tastypie_api.urls)),

    # Serve static
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.STATIC_ROOT}),

    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', \
                            {'url': 'static/cdr_stats/images/favicon.ico'}),
    (r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
)


urlpatterns += urlpatterns_cdr
urlpatterns += urlpatterns_cdr_alert
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_api_playgrounds
urlpatterns += urlpatterns_frontend_notification

cdr_stats/cdr_alert/models.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from country_dialcode.models import Country
from cdr_alert.constants import PERIOD, STATUS, ALARM_TYPE, \
    ALERT_CONDITION, ALERT_CONDITION_ADD_ON, ALARM_REPROT_STATUS


class AlertRemovePrefix(models.Model):
    """This defines the Alert Remove Prefix
    Define the list of prefixes that need to be removed from the dialed digits, 
    assuming the phone numbers are in the format 5559004432, with the signifcant digits
    9004432, the prefix 555 needs to be removed to analyse the phone numbers.

    **Attributes**:

        * ``label`` - Label for the custom prefix
        * ``prefix`` - Prefix value

    **Name of DB table**: alarm
    """
    label = models.CharField(max_length=100, verbose_name=_('Label'))
    prefix = models.CharField(max_length=100, unique=True,
                              verbose_name=_('Prefix'))
    created_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name=_('Date'))
    updated_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s' % (self.label)

    class Meta:
        verbose_name = _("Alert Remove Prefix")
        verbose_name_plural = _("Alert Remove Prefixes")
        db_table = "alert_remove_prefix"


class Alarm(models.Model):
    """This defines the Alarm

    **Attributes**:

        * ``user`` -
        * ``name`` - Alarm name
        * ``period`` - Day | Week | Month
        * ``type`` - ALOC (average length of call) ; ASR (answer seize ratio)
        * ``alert_condition`` -
        * ``alert_value`` - Input the value for the alert
        * ``alert_condition_add_on`` -
        * ``status`` - Inactive | Active
        * ``email_to_send_alarm`` - email_to

    **Name of DB table**: alert
    """
    user = models.ForeignKey('auth.User', related_name='Alarm_owner')
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    period = models.PositiveIntegerField(choices=list(PERIOD), default=1,
                                verbose_name=_('Period'),
                                help_text=_('Interval to apply alarm'))
    type = models.PositiveIntegerField(choices=list(ALARM_TYPE), default=1,
                                verbose_name=_('Type'),
                                help_text=_('ALOC (average length of call) ; ASR (answer seize ratio) ; CIC (Consecutive Incomplete Calls) '))
    alert_condition = models.PositiveIntegerField(choices=list(ALERT_CONDITION),
                                                  default=1,
                                                  verbose_name=_('Condition'))
    alert_value = models.DecimalField(verbose_name=_('Value'), max_digits=5,
                                decimal_places=2, blank=True, null=True,
                                help_text=_('Input the value for the alert'))
    alert_condition_add_on = models.PositiveIntegerField(choices=list(ALERT_CONDITION_ADD_ON),
                                                         default=1)
    status = models.PositiveIntegerField(choices=list(STATUS), default=1,
                                         verbose_name=_('Status'))

    email_to_send_alarm = models.EmailField(max_length=100,
                                    verbose_name=_('Email to send alarm'))
    created_date = models.DateTimeField(auto_now_add=True,
                                        verbose_name=_('Date'))
    updated_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s' % (self.name)

    class Meta:
        permissions = (
            ("alert_settings", _('Can see alarms')),
        )
        verbose_name = _("Alarm")
        verbose_name_plural = _("Alarms")
        db_table = "alert"


class AlarmReport(models.Model):
    """This defines the Alarm report

    **Attributes**:

        * ``alarm`` - Alarm name
        * ``calculatedvalue`` - Input the value for the alert
        * ``daterun`` -

    **Name of DB table**: alert_report
    """
    alarm = models.ForeignKey(Alarm, verbose_name=_('Alarm'),
                              help_text=_("Select Alarm"))
    calculatedvalue = models.DecimalField(verbose_name=_('Calculated value'),
                                          max_digits=10, decimal_places=3,
                                          blank=True, null=True)
    status = models.PositiveIntegerField(choices=list(ALARM_REPROT_STATUS),
                        default=1, verbose_name=_('Status'))

    daterun = models.DateTimeField(auto_now=True, verbose_name=_('Date'))

    def __unicode__(self):
        return '%s' % (self.alarm)

    class Meta:
        permissions = (
            ("alarm_report", _('Can see alarm report')),
        )
        verbose_name = _("Alarm Report")
        verbose_name_plural = _("Alarms Report")
        db_table = "alert_report"


class Blacklist(models.Model):
    """This defines the Blacklist

    **Attributes**:

        * ``user`` -
        * ``phonenumber_prefix`` -
        * ``country`` -

    **Name of DB table**: alert_blacklist
    """
    user = models.ForeignKey('auth.User', related_name='Blacklist_owner')
    phonenumber_prefix = models.PositiveIntegerField(blank=False, null=False)
    country = models.ForeignKey(Country, null=True, blank=True,
                                verbose_name=_("Country"),
                                help_text=_("Select Country"))

    def __unicode__(self):
        return '[%s] %s' % (self.id, self.phonenumber_prefix)

    class Meta:
        permissions = (
            ("view_blacklist", _('Can see blacklist country/prefix')),
        )
        verbose_name = _("Blacklist")
        verbose_name_plural = _("Blacklist")
        db_table = "alert_blacklist"


class Whitelist(models.Model):
    """This defines the Blacklist

    **Attributes**:

        * ``user`` -
        * ``phonenumber_prefix`` -
        * ``country`` -

    **Name of DB table**: alert_whitelist
    """
    user = models.ForeignKey('auth.User', related_name='whitelist_owner')
    phonenumber_prefix = models.PositiveIntegerField(blank=False, null=False)
    country = models.ForeignKey(Country, null=True, blank=True,
                                verbose_name=_("Country"),
                                help_text=_("Select Country"))

    def __unicode__(self):
        return '[%s] %s' % (self.id, self.phonenumber_prefix)

    class Meta:
        permissions = (
            ("view_whitelist", _('Can see whitelist country/prefix')),
        )
        verbose_name = _("Whitelist")
        verbose_name_plural = _("Whitelist")
        db_table = "alert_whitelist"

cdr_stats/cdr_alert/forms.py
#
# CDR-Stats License
# http://www.cdr-stats.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2012 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _
from cdr_alert.models import Alarm, Blacklist, Whitelist
from cdr.functions_def import get_country_list


class BWCountryForm(forms.Form):
    """Blacklist/Whitelist by country form"""
    country = forms.ChoiceField(label=_('Country'), required=True,
                                choices=get_country_list())

    def __init__(self, *args, **kwargs):
        super(BWCountryForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['country']


class BWPrefixForm(forms.Form):
    """Blacklist/Whitelist by prefix form"""
    prefix = forms.CharField(label=_('Prefix'), required=False)

    def __init__(self, *args, **kwargs):
        super(BWPrefixForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['prefix']


class AlarmForm(ModelForm):
    """Alarm ModelForm"""

    class Meta:
        model = Alarm
        fields = ['name', 'period', 'type', 'alert_condition',
                  'alert_value', 'alert_condition_add_on', 'status',
                  'email_to_send_alarm']
        exclude = ('user',)


class AlarmReportForm(forms.Form):
    """alarm list form"""
    alarm = forms.ChoiceField(label=_("Alert"), required=False)

    def __init__(self, user, *args, **kwargs):
        super(AlarmReportForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['alarm']

        alarm_list_user = []
        alarm_list_user.append((0, '---'))
        alarm_list = Alarm.objects.values_list('id', 'name')\
            .filter(user=user).order_by('id')
        for i in alarm_list:
            alarm_list_user.append((i[0], i[1]))

        self.fields['alarm'].choices = alarm_list_user

cdr_stats/templates/frontend/cdr_alert/alarm/change.html
{% extends "frontend/master.html" %}
{% load i18n %}

{% block header %}
{% endblock %}

{% block content_header %}
{% endblock %}

{% block content %}
<h3>
    {% if action == 'update' %}
        {% trans "Update" %}
    {% else %}
        {% trans "Add" %}
    {% endif %}
    {% trans "Alarm" %}
    <small></small>
</h3>

<form class="well" method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
    {% for field in form %}
    <div class="row{% if field.errors %} control-group error{% endif %}">
        <div class="span2">
            <label class="control-label" for="{{ field.auto_id }}">
                {{ field.label }}
            </label>
        </div>
        <div class="span8">{{ field }}
            {% if field.errors %}
                <span class="help-inline">{{ field.errors|removetags:"ul li"|safe }}</span>
            {% endif %}
            <span class="help-block">{{ field.help_text }} </span>
        </div>
    </div>
    {% endfor %}
    <div class="actions">
        {% if action == 'update' %}
        <input id="update" type="submit" class="btn btn-primary" value="{% trans "Update" %}" />
        {% else %}
        <input id="add" type="submit" class="btn btn-primary" value="{% trans "Submit" %}" />
        {% endif %}
        &nbsp;&nbsp;
        {% if action == 'update' %}
         <input id="delete" name="delete" class="btn btn-danger" type="submit" value="{% trans "Delete" %}" />
        {% endif %}
    </div>
</form>

{% endblock %}

cdr_stats/templates/frontend/cdr_alert/alarm/list.html
{% extends "frontend/master.html" %}
{% load i18n pagination_tags cdr_extras common_tags icons %}

{% block title %}{% trans "Alert" %}{% endblock %}

{% block extra_head %}
    {% include "frontend/custom_jquery_select_all.html" %}
    <center>
        <h3>{% trans "alerts"|title %} <small>{% trans "list of alerts" %}</small></h3>
    </center>
{% endblock %}

{% block content %}
<script type="text/javascript">
    function add_button()
    {
        window.location = 'add/';
    }

    function delete_button()
    {
        $('#ListForm').submit();
    }
</script>

<div class="span12">
    <div class="row">
        <div class="btn-group">
            <button class="btn">{% trans "Action" %}</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                {% if perms.dialer_contact.delete_phonebook %}
                    <li><a href="#" onclick="delete_button()">{% trans "Delete selected" %}</a></li>
                {% endif %}
            </ul>
        </div>
        {% if perms.dialer_contact.add_phonebook %}
            <a class="btn btn-info" href="#" onclick="add_button()">{% trans "Add" %}</a>
        {% endif %}
    </div>
</div>
<br/><br/>
<div class="row">
    <div class="span12">
        <form method="POST" action="del/0/" enctype="multipart/form-data" id="ListForm">{% csrf_token %}
        <table class="table table-striped table-bordered table-condensed">
            <thead>
            <tr>
                <th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>
                <th>{% sort_link ALARM_COLUMN_NAME.id col_name_with_order.id  %}</th>
                <th>{% sort_link ALARM_COLUMN_NAME.name col_name_with_order.name  %}</th>
                <th>{% sort_link ALARM_COLUMN_NAME.period col_name_with_order.period  %}</th>
                <th>{% sort_link ALARM_COLUMN_NAME.type col_name_with_order.type  %}</th>
                <th>{% sort_link ALARM_COLUMN_NAME.alert_condition col_name_with_order.alert_condition  %}</th>
                <th>{% sort_link ALARM_COLUMN_NAME.alert_value col_name_with_order.alert_value  %}</th>
                <th>{% sort_link ALARM_COLUMN_NAME.status col_name_with_order.status  %}</th>
                <th>{% sort_link ALARM_COLUMN_NAME.updated_date col_name_with_order.updated_date  %}</th>
                <th>{% trans "Action" %}</th>
            </tr>
            </thead>
            {% if rows %}

            {% autopaginate rows PAGE_SIZE %}
            {% for row in rows %}
            <tr>
                <td><input type="checkbox" name="select" class="checkbox" value="{{ row.id }}" /></td>
                <td>{{ row.id }}</td>
                <td>{{ row.name }}</td>
                <td>{{ row.period|alarm_period }}</td>
                <td>{{ row.type|alarm_type }}</td>
                <td>{{ row.alert_condition|alarm_condition }}</td>
                <td>{{ row.alert_value }}</td>
                <td>{{ row.status|alarm_status }}</td>
                <td>{{ row.updated_date }}</td>
                <td>
                    {% if perms.cdr_alert.change_alarm %}
                        <a href="{{ row.id }}/" {% icon "page_edit" %} title="{% trans "Update alarm" %}"></a>
                    {% endif %}
                    {% if perms.cdr_alert.delete_alarm %}
                        <a id="id_delete_confirm" href="del/{{ row.id }}/" {% icon "delete" %} title="{% trans "Delete alarm" %}"></a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

            {% else %}
            <tr>
                <td colspan="10" align="center">
                    {% trans "no records found"|title %}
                </td>
            </tr>
            {% endif %}
        </table>
        <div align="right" class="show-rows">
            {% trans "total alarms"|title %} : {{ total_count }}
        </div>

        {% if rows %}
            {% paginate %}
        {% endif %}
        </form>
    </div>
</div>
{% endblock %}